import { PropertyInput } from '../types';

export const SAMPLE_PROPERTY_1: PropertyInput = {
  propertyName: 'Premium 2 BHK Apartment',
  location: 'Whitefield, Bengaluru',
  propertyType: 'Apartment',
  bhk: 2,
  builtUpArea: 1200,
  askingPrice: 8500000,
  expectedMonthlyRent: 32000,
  propertyAge: 4,
  floor: 8,
  totalFloors: 20,
  parking: 'Yes',
  furnishing: 'Semi-Furnished',
  monthlyMaintenance: 4000,
  downPayment: 2500000,
  loanInterestRate: 8.5,
  loanTenure: 20,
  otherExpenses: 25000,
};

export const SAMPLE_PROPERTY_2: PropertyInput = {
  propertyName: 'Modern High-Rise 3 BHK',
  location: 'Hitec City, Hyderabad',
  propertyType: 'Apartment',
  bhk: 3,
  builtUpArea: 1850,
  askingPrice: 14500000,
  expectedMonthlyRent: 58000,
  propertyAge: 2,
  floor: 14,
  totalFloors: 28,
  parking: 'Yes',
  furnishing: 'Fully Furnished',
  monthlyMaintenance: 6500,
  downPayment: 4000000,
  loanInterestRate: 8.4,
  loanTenure: 20,
  otherExpenses: 35000,
};

export const SAMPLE_PROPERTY_3: PropertyInput = {
  propertyName: 'Boutique 4 BHK Villa',
  location: 'North Goa',
  propertyType: 'Villa',
  bhk: 4,
  builtUpArea: 2800,
  askingPrice: 28000000,
  expectedMonthlyRent: 110000,
  propertyAge: 1,
  floor: 1,
  totalFloors: 2,
  parking: 'Yes',
  furnishing: 'Fully Furnished',
  monthlyMaintenance: 12000,
  downPayment: 8500000,
  loanInterestRate: 8.65,
  loanTenure: 15,
  otherExpenses: 60000,
};
